### ISSUE TITLE
Thanks! It helped finding correct guid.

### ISSUE THREAD

**Issue by gpuclub** [renaatd/winusb-deviceinterfaceguid#1]
I wonder if there is a pure C++ code that enumerates the devices. The rest of my proj is in VC++.

**Comment by renaatd** [comment]
Glad it helped!
This C# implementation uses Vanara CfgMgr32 and SetupApi. These are thin wrappers around the native Windows API. It should be fairly straightforward to translate this C# to C/C++ using https://github.com/dahall/Vanara/tree/master/PInvoke/SetupAPI
